version: 2.1
orbs:
  docker: circleci/docker@1.4.0

workflows:
  build-and-test:
    jobs:
      - build_docker_image:
          filters:
            branches:
              only: main

jobs:
  build_docker_image:
    machine:
      enabled: true
      image: cimg/deploy:2023.12
    resource_class: diegopavani2/ubunturesource
    steps:
      - checkout
      - run:
          name: Install Docker
          command: |
            sudo apt-get update
            sudo apt-get install -y docker.io
      - docker/login:
          username: DOCKERHUB_LOGIN
          password: DOCKERHUB_PASSWORD
      - run:
          name: Build Docker Image
          command: |
            sudo docker build -t diegopavani2/mega-frontend-ceps:latest .
      - run:
          name: Push Docker Image
          command: |
            sudo docker push diegopavani2/mega-frontend-ceps:latest
