version: 2.1
orbs:
  docker: circleci/docker@1.4.0

workflows:
  build-and-test:
    jobs:
      - build_docker_image:
          filters:
            branches:
              only: main

jobs:
  build_docker_image:
    build:
    docker:
      - image: cimg/deploy:2023.12.1-node
    steps:
      - checkout
      - run:
          name: Docker Login
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_LOGIN" --password-stdin
      - run:
          name: Build Docker Image
          command: |
            sudo systemctl start docker
            sudo docker build -t diegopavani2/mega-frontend-ceps:latest .
      - run:
          name: Push Docker Image
          command: |
            sudo docker push diegopavani2/mega-frontend-ceps:latest
