version: 2.1

workflows:
  build-and-test:
    jobs:
      - build_docker_image:
          filters:
            branches:
              only:
                - main
                - dev

jobs:
  build_docker_image:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Docker Login
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_LOGIN" --password-stdin
      - run:
          name: Determine Docker Image Tag
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              echo 'export IMAGE_TAG=latest' >> $BASH_ENV
            elif [ "${CIRCLE_BRANCH}" == "dev" ]; then
              echo 'export IMAGE_TAG=dev' >> $BASH_ENV
            else
              echo 'export IMAGE_TAG=other' >> $BASH_ENV
            fi
            source $BASH_ENV
      - run:
          name: Build Docker Image
          command: |
            docker build -t diegopavani2/mega-frontend-ceps:${IMAGE_TAG} .
      - run:
          name: Push Docker Image
          command: |
            docker push diegopavani2/mega-frontend-ceps:${IMAGE_TAG}
